apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-suite
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://cs-jmiller-ddu.platform9.net/qbert/v4/932b0f07583842a197464d602fffd7ce/clusters/03e3ae46-1fd8-410a-b522-98bc31ccebe2/k8sapi
  project: default
  source:
    path: apps
    repoURL: 'https://github.com/jeremymv2/argo-app-of-apps.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 2
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
